server:
  port: 8080
  
spring:  
  cloud:
    gateway:
      routes:
        - id: subscriptionRoute
          uri: http://localhost:8083
          predicates:
           - Path=/subscription/**
        - id: courseRoute
          uri: lb://COURSE-SERVICE
          predicates:
           - Path=/course/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-respons-header, custom-user-response-header
